/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iutpj_user;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author KAWSAR
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    UserSocket userSocket;
    public SignUp(UserSocket usersocket) {
        initComponents();
        txtUsername.setFocusable(true);
        this.userSocket = usersocket;
        this.userSocket.setCurrentJFrame(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LeftPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        RightPanel = new javax.swing.JPanel();
        WelcomeLabel = new javax.swing.JLabel();
        closeLabel = new javax.swing.JLabel();
        minimizeLabel = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        SignUpButton = new javax.swing.JButton();
        AlreadyAccButton = new javax.swing.JButton();
        leftSeparator = new javax.swing.JSeparator();
        ConfirmPasswordField = new javax.swing.JPasswordField();
        ConfirmPasswordLabel = new javax.swing.JLabel();
        UserNameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        EmailLabel = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        InstitutionLabel = new javax.swing.JLabel();
        txtInstitution = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LeftPanel.setBackground(new java.awt.Color(54, 33, 89));
        LeftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/newlogo.png"))); // NOI18N
        LeftPanel.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 180, 170));

        getContentPane().add(LeftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 560));

        RightPanel.setBackground(new java.awt.Color(255, 255, 255));
        RightPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WelcomeLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 38)); // NOI18N
        WelcomeLabel.setForeground(new java.awt.Color(54, 33, 89));
        WelcomeLabel.setText("Sign up for IUTPJ");
        RightPanel.add(WelcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 360, 70));

        closeLabel.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        closeLabel.setForeground(new java.awt.Color(54, 33, 89));
        closeLabel.setText("x");
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
        });
        RightPanel.add(closeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 30, 20));

        minimizeLabel.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        minimizeLabel.setForeground(new java.awt.Color(54, 33, 89));
        minimizeLabel.setText("_");
        minimizeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLabelMouseClicked(evt);
            }
        });
        RightPanel.add(minimizeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, -10, 30, 40));

        txtUsername.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(102, 102, 102));
        txtUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        txtUsername.setSelectionColor(new java.awt.Color(110, 89, 222));
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsernameFocusLost(evt);
            }
        });
        RightPanel.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 270, 30));

        SignUpButton.setBackground(new java.awt.Color(54, 33, 89));
        SignUpButton.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        SignUpButton.setForeground(new java.awt.Color(54, 33, 89));
        SignUpButton.setText("Sign Up");
        SignUpButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(54, 33, 89)));
        SignUpButton.setContentAreaFilled(false);
        SignUpButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SignUpButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });
        RightPanel.add(SignUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 90, 40));

        AlreadyAccButton.setBackground(new java.awt.Color(54, 33, 89));
        AlreadyAccButton.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        AlreadyAccButton.setForeground(new java.awt.Color(54, 33, 89));
        AlreadyAccButton.setText("Already have an account?");
        AlreadyAccButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(54, 33, 89)));
        AlreadyAccButton.setContentAreaFilled(false);
        AlreadyAccButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AlreadyAccButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AlreadyAccButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlreadyAccButtonButtonActionPerformed(evt);
            }
        });
        RightPanel.add(AlreadyAccButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 270, 40));
        RightPanel.add(leftSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 390, 20));

        ConfirmPasswordField.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        ConfirmPasswordField.setForeground(new java.awt.Color(102, 102, 102));
        ConfirmPasswordField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        ConfirmPasswordField.setSelectionColor(new java.awt.Color(110, 89, 222));
        RightPanel.add(ConfirmPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 200, 30));

        ConfirmPasswordLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 20)); // NOI18N
        ConfirmPasswordLabel.setForeground(new java.awt.Color(54, 33, 89));
        ConfirmPasswordLabel.setText("Confirm Password");
        RightPanel.add(ConfirmPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 180, 30));

        UserNameLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 20)); // NOI18N
        UserNameLabel.setForeground(new java.awt.Color(54, 33, 89));
        UserNameLabel.setText("Username");
        RightPanel.add(UserNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 120, 30));

        PasswordLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 20)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(54, 33, 89));
        PasswordLabel.setText("Password");
        RightPanel.add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 120, 30));

        PasswordField.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        PasswordField.setForeground(new java.awt.Color(102, 102, 102));
        PasswordField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        PasswordField.setSelectionColor(new java.awt.Color(110, 89, 222));
        RightPanel.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 270, 30));

        EmailLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 20)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(54, 33, 89));
        EmailLabel.setText("Email");
        RightPanel.add(EmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 120, 30));

        txtEmail.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(102, 102, 102));
        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        txtEmail.setSelectionColor(new java.awt.Color(110, 89, 222));
        RightPanel.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 270, 30));

        InstitutionLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 20)); // NOI18N
        InstitutionLabel.setForeground(new java.awt.Color(54, 33, 89));
        InstitutionLabel.setText("Institution");
        RightPanel.add(InstitutionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 120, 30));

        txtInstitution.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        txtInstitution.setForeground(new java.awt.Color(102, 102, 102));
        txtInstitution.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        txtInstitution.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtInstitution.setSelectionColor(new java.awt.Color(110, 89, 222));
        RightPanel.add(txtInstitution, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 302, 270, -1));

        getContentPane().add(RightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 530, 560));

        setSize(new java.awt.Dimension(954, 556));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AlreadyAccButtonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlreadyAccButtonButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_AlreadyAccButtonButtonActionPerformed

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_closeLabelMouseClicked

    private void minimizeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLabelMouseClicked
        this.setExtendedState(JFrame.ICONIFIED);      // TODO add your handling code here:
    }//GEN-LAST:event_minimizeLabelMouseClicked

    private void txtUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusGained
        if(txtUsername.getText().equals("Enter Username")) 
        {
            txtUsername.setText("");
        }
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameFocusGained

    private void txtUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusLost
        if(txtUsername.getText().equals("")) 
        {
            txtUsername.setText("Enter Username");
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameFocusLost

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
       String usrname = txtUsername.getText();
        String password = PasswordField.getText();
        String confirmPassword = ConfirmPasswordField.getText();

        if (password.equals(confirmPassword) == false) {
            ConfirmPasswordField.setText("");
            JOptionPane.showMessageDialog(null, "Password didn't match", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (userSocket.signUp(usrname, password)) {

            JOptionPane.showMessageDialog(null, "SignUp Successfull", "SignUP", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "SignUp Failed", "SignUp!!!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SignUpButtonActionPerformed
    static int xx, yy;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx=evt.getX();
        yy=evt.getY();// TODO add your handling code here:
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x, y;
        x=evt.getXOnScreen();
        y=evt.getYOnScreen();
        this.setLocation(x-xx,y-yy);// TODO add your handling code here:
    }//GEN-LAST:event_formMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlreadyAccButton;
    private javax.swing.JPasswordField ConfirmPasswordField;
    private javax.swing.JLabel ConfirmPasswordLabel;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel InstitutionLabel;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JLabel UserNameLabel;
    private javax.swing.JLabel WelcomeLabel;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JSeparator leftSeparator;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel minimizeLabel;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtInstitution;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
